<?php

declare(strict_types=1);

namespace Database\Seeders\Snapshots\Snapshot20250122;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class LanguagesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        DB::table('languages')->delete();

        DB::table('languages')->insert([
            0 => [
                'id' => 1,
                'code' => 'aa',
                'name' => 'Afar',
                'endonym' => 'Afaraf',
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'code' => 'ab',
                'name' => 'Abkhazian',
                'endonym' => 'аҧсуа бызшәа|аҧсшәа',
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'code' => 'ae',
                'name' => 'Avestan',
                'endonym' => 'avesta',
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'code' => 'af',
                'name' => 'Afrikaans',
                'endonym' => 'Afrikaans',
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'code' => 'ak',
                'name' => 'Akan',
                'endonym' => 'Akan',
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'code' => 'am',
                'name' => 'Amharic',
                'endonym' => 'አማርኛ',
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'code' => 'an',
                'name' => 'Aragonese',
                'endonym' => 'aragonés',
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'code' => 'ar',
                'name' => 'Arabic',
                'endonym' => 'العربية',
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'code' => 'as',
                'name' => 'Assamese',
                'endonym' => 'অসমীয়া',
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'code' => 'ath',
                'name' => 'Athabaskan languages',
                'endonym' => 'Athabascan|Athapaskan|Athapascan|Dene',
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'code' => 'av',
                'name' => 'Avaric',
                'endonym' => 'авар мацӀ|магӀарул мацӀ',
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'code' => 'ay',
                'name' => 'Aymara',
                'endonym' => 'aymar aru',
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'code' => 'az',
                'name' => 'Azerbaijani',
                'endonym' => 'azərbaycan dili',
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'id' => 14,
                'code' => 'ba',
                'name' => 'Bashkir',
                'endonym' => 'башҡорт теле',
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'id' => 15,
                'code' => 'be',
                'name' => 'Belarusian',
                'endonym' => 'беларуская мова',
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'id' => 16,
                'code' => 'ber',
                'name' => 'Berber languages',
                'endonym' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ|ⵜⵎⵣⵗⵜ|Tamaziɣt',
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'id' => 17,
                'code' => 'bg',
                'name' => 'Bulgarian',
                'endonym' => 'български език',
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'id' => 18,
                'code' => 'bh',
                'name' => 'Bihari languages',
                'endonym' => 'भोजपुरी',
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 19,
                'code' => 'bi',
                'name' => 'Bislama',
                'endonym' => 'Bislama',
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'id' => 20,
                'code' => 'bm',
                'name' => 'Bambara',
                'endonym' => 'bamanankan',
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'id' => 21,
                'code' => 'bn',
                'name' => 'Bengali',
                'endonym' => 'বাংলা',
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'id' => 22,
                'code' => 'bo',
                'name' => 'Tibetan',
                'endonym' => 'བོད་ཡིག',
                'created_at' => null,
                'updated_at' => null,
            ],
            22 => [
                'id' => 23,
                'code' => 'br',
                'name' => 'Breton',
                'endonym' => 'brezhoneg',
                'created_at' => null,
                'updated_at' => null,
            ],
            23 => [
                'id' => 24,
                'code' => 'bs',
                'name' => 'Bosnian',
                'endonym' => 'bosanski jezik',
                'created_at' => null,
                'updated_at' => null,
            ],
            24 => [
                'id' => 25,
                'code' => 'bwg',
                'name' => 'Barwe',
                'endonym' => 'Barwe',
                'created_at' => null,
                'updated_at' => null,
            ],
            25 => [
                'id' => 26,
                'code' => 'ca',
                'name' => 'Catalan|Valencian',
                'endonym' => 'català|valencià',
                'created_at' => null,
                'updated_at' => null,
            ],
            26 => [
                'id' => 27,
                'code' => 'cal',
                'name' => 'Carolinian',
                'endonym' => 'Carolinian',
                'created_at' => null,
                'updated_at' => null,
            ],
            27 => [
                'id' => 28,
                'code' => 'ce',
                'name' => 'Chechen',
                'endonym' => 'нохчийн мотт',
                'created_at' => null,
                'updated_at' => null,
            ],
            28 => [
                'id' => 29,
                'code' => 'ch',
                'name' => 'Chamorro',
                'endonym' => 'Chamoru',
                'created_at' => null,
                'updated_at' => null,
            ],
            29 => [
                'id' => 30,
                'code' => 'chp',
                'name' => 'Chipewyan',
                'endonym' => 'ᑌᓀᓲᒢᕄᓀ|Dëne Sųłiné',
                'created_at' => null,
                'updated_at' => null,
            ],
            30 => [
                'id' => 31,
                'code' => 'cnr',
                'name' => 'Montenegrin',
                'endonym' => 'црногорски|crnogorski',
                'created_at' => null,
                'updated_at' => null,
            ],
            31 => [
                'id' => 32,
                'code' => 'co',
                'name' => 'Corsican',
                'endonym' => 'corsu|lingua corsa',
                'created_at' => null,
                'updated_at' => null,
            ],
            32 => [
                'id' => 33,
                'code' => 'coa',
                'name' => 'Malay, Cocos Islands|Cocos Malay',
                'endonym' => 'Basa Pulu Cocos',
                'created_at' => null,
                'updated_at' => null,
            ],
            33 => [
                'id' => 34,
                'code' => 'cr',
                'name' => 'Cree',
                'endonym' => 'ᓀᐦᐃᔭᐍᐏᐣ',
                'created_at' => null,
                'updated_at' => null,
            ],
            34 => [
                'id' => 35,
                'code' => 'crs',
                'name' => 'Seselwa Creole French',
                'endonym' => 'kreol|seselwa|Seychellois Creole',
                'created_at' => null,
                'updated_at' => null,
            ],
            35 => [
                'id' => 36,
                'code' => 'cs',
                'name' => 'Czech',
                'endonym' => 'čeština|český jazyk',
                'created_at' => null,
                'updated_at' => null,
            ],
            36 => [
                'id' => 37,
                'code' => 'cu',
                'name' => 'Church Slavic|Old Slavonic|Church Slavonic|Old Bulgarian|Old Church Slavonic',
                'endonym' => 'ѩзыкъ словѣньскъ',
                'created_at' => null,
                'updated_at' => null,
            ],
            37 => [
                'id' => 38,
                'code' => 'cv',
                'name' => 'Chuvash',
                'endonym' => 'чӑваш чӗлхи',
                'created_at' => null,
                'updated_at' => null,
            ],
            38 => [
                'id' => 39,
                'code' => 'cy',
                'name' => 'Welsh',
                'endonym' => 'Cymraeg',
                'created_at' => null,
                'updated_at' => null,
            ],
            39 => [
                'id' => 40,
                'code' => 'da',
                'name' => 'Danish',
                'endonym' => 'dansk',
                'created_at' => null,
                'updated_at' => null,
            ],
            40 => [
                'id' => 41,
                'code' => 'de',
                'name' => 'German',
                'endonym' => 'Deutsch',
                'created_at' => null,
                'updated_at' => null,
            ],
            41 => [
                'id' => 42,
                'code' => 'den',
                'name' => 'Slavey|Slave|Slavé',
                'endonym' => 'Dene K\'e',
                'created_at' => null,
                'updated_at' => null,
            ],
            42 => [
                'id' => 43,
                'code' => 'dgr',
                'name' => 'Dogrib',
                'endonym' => 'Tłįchǫ',
                'created_at' => null,
                'updated_at' => null,
            ],
            43 => [
                'id' => 44,
                'code' => 'din',
                'name' => 'Dinka',
                'endonym' => 'Thuɔŋjäŋ|Thuɔŋ ee Jieng|Jieng',
                'created_at' => null,
                'updated_at' => null,
            ],
            44 => [
                'id' => 45,
                'code' => 'dv',
                'name' => 'Divehi|Dhivehi|Maldivian',
                'endonym' => 'ދިވެހި',
                'created_at' => null,
                'updated_at' => null,
            ],
            45 => [
                'id' => 46,
                'code' => 'dz',
                'name' => 'Dzongkha',
                'endonym' => 'རྫོང་ཁ',
                'created_at' => null,
                'updated_at' => null,
            ],
            46 => [
                'id' => 47,
                'code' => 'ee',
                'name' => 'Ewe',
                'endonym' => 'Eʋegbe',
                'created_at' => null,
                'updated_at' => null,
            ],
            47 => [
                'id' => 48,
                'code' => 'el',
                'name' => 'Greek, Modern (1453-)',
                'endonym' => 'ελληνική γλώσσα|ελληνικά',
                'created_at' => null,
                'updated_at' => null,
            ],
            48 => [
                'id' => 49,
                'code' => 'en',
                'name' => 'English',
                'endonym' => 'English',
                'created_at' => null,
                'updated_at' => null,
            ],
            49 => [
                'id' => 50,
                'code' => 'eo',
                'name' => 'Esperanto',
                'endonym' => 'Esperanto',
                'created_at' => null,
                'updated_at' => null,
            ],
            50 => [
                'id' => 51,
                'code' => 'es',
                'name' => 'Spanish|Castilian',
                'endonym' => 'español|castellano',
                'created_at' => null,
                'updated_at' => null,
            ],
            51 => [
                'id' => 52,
                'code' => 'et',
                'name' => 'Estonian',
                'endonym' => 'eesti|eesti keel',
                'created_at' => null,
                'updated_at' => null,
            ],
            52 => [
                'id' => 53,
                'code' => 'eu',
                'name' => 'Basque',
                'endonym' => 'euskara|euskera',
                'created_at' => null,
                'updated_at' => null,
            ],
            53 => [
                'id' => 54,
                'code' => 'fa',
                'name' => 'Persian',
                'endonym' => 'فارسی',
                'created_at' => null,
                'updated_at' => null,
            ],
            54 => [
                'id' => 55,
                'code' => 'ff',
                'name' => 'Fulah',
                'endonym' => 'Fulfulde|Pulaar|Pular',
                'created_at' => null,
                'updated_at' => null,
            ],
            55 => [
                'id' => 56,
                'code' => 'fi',
                'name' => 'Finnish',
                'endonym' => 'suomi|suomen kieli',
                'created_at' => null,
                'updated_at' => null,
            ],
            56 => [
                'id' => 57,
                'code' => 'fil',
                'name' => 'Filipino',
                'endonym' => 'Wikang Filipino',
                'created_at' => null,
                'updated_at' => null,
            ],
            57 => [
                'id' => 58,
                'code' => 'fj',
                'name' => 'Fijian',
                'endonym' => 'vosa Vakaviti',
                'created_at' => null,
                'updated_at' => null,
            ],
            58 => [
                'id' => 59,
                'code' => 'fo',
                'name' => 'Faroese',
                'endonym' => 'føroyskt',
                'created_at' => null,
                'updated_at' => null,
            ],
            59 => [
                'id' => 60,
                'code' => 'fr',
                'name' => 'French',
                'endonym' => 'français|langue française',
                'created_at' => null,
                'updated_at' => null,
            ],
            60 => [
                'id' => 61,
                'code' => 'fy',
                'name' => 'Western Frisian',
                'endonym' => 'Frysk',
                'created_at' => null,
                'updated_at' => null,
            ],
            61 => [
                'id' => 62,
                'code' => 'ga',
                'name' => 'Irish',
                'endonym' => 'Gaeilge',
                'created_at' => null,
                'updated_at' => null,
            ],
            62 => [
                'id' => 63,
                'code' => 'gd',
                'name' => 'Gaelic|Scottish Gaelic',
                'endonym' => 'Gàidhlig',
                'created_at' => null,
                'updated_at' => null,
            ],
            63 => [
                'id' => 64,
                'code' => 'gil',
                'name' => 'Gilbertese',
                'endonym' => 'taetae ni Kiribati',
                'created_at' => null,
                'updated_at' => null,
            ],
            64 => [
                'id' => 65,
                'code' => 'gl',
                'name' => 'Galician',
                'endonym' => 'galego',
                'created_at' => null,
                'updated_at' => null,
            ],
            65 => [
                'id' => 66,
                'code' => 'gn',
                'name' => 'Guarani',
                'endonym' => 'Avañe\'ẽ',
                'created_at' => null,
                'updated_at' => null,
            ],
            66 => [
                'id' => 67,
                'code' => 'gu',
                'name' => 'Gujarati',
                'endonym' => 'ગુજરાતી',
                'created_at' => null,
                'updated_at' => null,
            ],
            67 => [
                'id' => 68,
                'code' => 'gv',
                'name' => 'Manx',
                'endonym' => 'Gaelg|Gailck',
                'created_at' => null,
                'updated_at' => null,
            ],
            68 => [
                'id' => 69,
                'code' => 'gwi',
                'name' => 'Gwich´in',
                'endonym' => 'Gwich´in',
                'created_at' => null,
                'updated_at' => null,
            ],
            69 => [
                'id' => 70,
                'code' => 'ha',
                'name' => 'Hausa',
                'endonym' => 'Hausa|هَوُسَ',
                'created_at' => null,
                'updated_at' => null,
            ],
            70 => [
                'id' => 71,
                'code' => 'he',
                'name' => 'Hebrew',
                'endonym' => 'עברית',
                'created_at' => null,
                'updated_at' => null,
            ],
            71 => [
                'id' => 72,
                'code' => 'hi',
                'name' => 'Hindi',
                'endonym' => 'हिन्दी|हिंदी',
                'created_at' => null,
                'updated_at' => null,
            ],
            72 => [
                'id' => 73,
                'code' => 'hif',
                'name' => 'Fiji Hindi|Fijian Hindi',
                'endonym' => 'फ़िजी हिंदी|Fiji Baat',
                'created_at' => null,
                'updated_at' => null,
            ],
            73 => [
                'id' => 74,
                'code' => 'ho',
                'name' => 'Hiri Motu',
                'endonym' => 'Hiri Motu',
                'created_at' => null,
                'updated_at' => null,
            ],
            74 => [
                'id' => 75,
                'code' => 'hr',
                'name' => 'Croatian',
                'endonym' => 'hrvatski jezik',
                'created_at' => null,
                'updated_at' => null,
            ],
            75 => [
                'id' => 76,
                'code' => 'ht',
                'name' => 'Haitian|Haitian Creole',
                'endonym' => 'Kreyòl ayisyen',
                'created_at' => null,
                'updated_at' => null,
            ],
            76 => [
                'id' => 77,
                'code' => 'hu',
                'name' => 'Hungarian',
                'endonym' => 'Magyar',
                'created_at' => null,
                'updated_at' => null,
            ],
            77 => [
                'id' => 78,
                'code' => 'hy',
                'name' => 'Armenian',
                'endonym' => 'Հայերեն',
                'created_at' => null,
                'updated_at' => null,
            ],
            78 => [
                'id' => 79,
                'code' => 'hz',
                'name' => 'Herero',
                'endonym' => 'Otjiherero',
                'created_at' => null,
                'updated_at' => null,
            ],
            79 => [
                'id' => 80,
                'code' => 'ia',
                'name' => 'Interlingua (International Auxiliary Language Association)',
                'endonym' => 'Interlingua',
                'created_at' => null,
                'updated_at' => null,
            ],
            80 => [
                'id' => 81,
                'code' => 'id',
                'name' => 'Indonesian',
                'endonym' => 'Bahasa Indonesia',
                'created_at' => null,
                'updated_at' => null,
            ],
            81 => [
                'id' => 82,
                'code' => 'ie',
                'name' => 'Interlingue|Occidental',
                'endonym' => 'Originally called Occidental; then Interlingue after WWII',
                'created_at' => null,
                'updated_at' => null,
            ],
            82 => [
                'id' => 83,
                'code' => 'ig',
                'name' => 'Igbo',
                'endonym' => 'Asụsụ Igbo',
                'created_at' => null,
                'updated_at' => null,
            ],
            83 => [
                'id' => 84,
                'code' => 'ii',
                'name' => 'Sichuan Yi|Nuosu',
                'endonym' => 'ꆈꌠ꒿ Nuosuhxop',
                'created_at' => null,
                'updated_at' => null,
            ],
            84 => [
                'id' => 85,
                'code' => 'ik',
                'name' => 'Inupiaq',
                'endonym' => 'Iñupiaq|Iñupiatun',
                'created_at' => null,
                'updated_at' => null,
            ],
            85 => [
                'id' => 86,
                'code' => 'io',
                'name' => 'Ido',
                'endonym' => 'Ido',
                'created_at' => null,
                'updated_at' => null,
            ],
            86 => [
                'id' => 87,
                'code' => 'is',
                'name' => 'Icelandic',
                'endonym' => 'Íslenska',
                'created_at' => null,
                'updated_at' => null,
            ],
            87 => [
                'id' => 88,
                'code' => 'it',
                'name' => 'Italian',
                'endonym' => 'italiano',
                'created_at' => null,
                'updated_at' => null,
            ],
            88 => [
                'id' => 89,
                'code' => 'iu',
                'name' => 'Inuktitut',
                'endonym' => 'ᐃᓄᒃᑎᑐᑦ',
                'created_at' => null,
                'updated_at' => null,
            ],
            89 => [
                'id' => 90,
                'code' => 'ja',
                'name' => 'Japanese',
                'endonym' => '日本語 (にほんご)',
                'created_at' => null,
                'updated_at' => null,
            ],
            90 => [
                'id' => 91,
                'code' => 'jv',
                'name' => 'Javanese',
                'endonym' => 'basa Jawa',
                'created_at' => null,
                'updated_at' => null,
            ],
            91 => [
                'id' => 92,
                'code' => 'ka',
                'name' => 'Georgian',
                'endonym' => 'ქართული',
                'created_at' => null,
                'updated_at' => null,
            ],
            92 => [
                'id' => 93,
                'code' => 'kck',
                'name' => 'Kalanga|TjiKalanga',
                'endonym' => 'Ikalanga',
                'created_at' => null,
                'updated_at' => null,
            ],
            93 => [
                'id' => 94,
                'code' => 'kg',
                'name' => 'Kongo',
                'endonym' => 'KiKongo',
                'created_at' => null,
                'updated_at' => null,
            ],
            94 => [
                'id' => 95,
                'code' => 'khi',
                'name' => 'Khoisan languages',
                'endonym' => 'Khoe-Sān',
                'created_at' => null,
                'updated_at' => null,
            ],
            95 => [
                'id' => 96,
                'code' => 'ki',
                'name' => 'Kikuyu|Gikuyu',
                'endonym' => 'Gĩkũyũ',
                'created_at' => null,
                'updated_at' => null,
            ],
            96 => [
                'id' => 97,
                'code' => 'kj',
                'name' => 'Kuanyama|Kwanyama',
                'endonym' => 'Kuanyama',
                'created_at' => null,
                'updated_at' => null,
            ],
            97 => [
                'id' => 98,
                'code' => 'kk',
                'name' => 'Kazakh',
                'endonym' => 'қазақ тілі',
                'created_at' => null,
                'updated_at' => null,
            ],
            98 => [
                'id' => 99,
                'code' => 'kl',
                'name' => 'Kalaallisut|Greenlandic',
                'endonym' => 'kalaallisut|kalaallit oqaasii',
                'created_at' => null,
                'updated_at' => null,
            ],
            99 => [
                'id' => 100,
                'code' => 'km',
                'name' => 'Central Khmer',
                'endonym' => 'ខ្មែរ|ខេមរភាសា|ភាសាខ្មែរ',
                'created_at' => null,
                'updated_at' => null,
            ],
            100 => [
                'id' => 101,
                'code' => 'kn',
                'name' => 'Kannada',
                'endonym' => 'ಕನ್ನಡ',
                'created_at' => null,
                'updated_at' => null,
            ],
            101 => [
                'id' => 102,
                'code' => 'ko',
                'name' => 'Korean',
                'endonym' => '한국어 (韓國語)|조선어 (朝鮮語)',
                'created_at' => null,
                'updated_at' => null,
            ],
            102 => [
                'id' => 103,
                'code' => 'kr',
                'name' => 'Kanuri',
                'endonym' => 'Kanuri',
                'created_at' => null,
                'updated_at' => null,
            ],
            103 => [
                'id' => 104,
                'code' => 'ks',
                'name' => 'Kashmiri',
                'endonym' => 'कश्मीरी|كشميري',
                'created_at' => null,
                'updated_at' => null,
            ],
            104 => [
                'id' => 105,
                'code' => 'ku',
                'name' => 'Kurdish',
                'endonym' => 'Kurdî|كوردی',
                'created_at' => null,
                'updated_at' => null,
            ],
            105 => [
                'id' => 106,
                'code' => 'kv',
                'name' => 'Komi',
                'endonym' => 'коми кыв',
                'created_at' => null,
                'updated_at' => null,
            ],
            106 => [
                'id' => 107,
                'code' => 'kw',
                'name' => 'Cornish',
                'endonym' => 'Kernewek',
                'created_at' => null,
                'updated_at' => null,
            ],
            107 => [
                'id' => 108,
                'code' => 'ky',
                'name' => 'Kirghiz|Kyrgyz',
                'endonym' => 'кыргыз тили',
                'created_at' => null,
                'updated_at' => null,
            ],
            108 => [
                'id' => 109,
                'code' => 'la',
                'name' => 'Latin',
                'endonym' => 'latine|lingua latina',
                'created_at' => null,
                'updated_at' => null,
            ],
            109 => [
                'id' => 110,
                'code' => 'lb',
                'name' => 'Luxembourgish|Letzeburgesch',
                'endonym' => 'Lëtzebuergesch',
                'created_at' => null,
                'updated_at' => null,
            ],
            110 => [
                'id' => 111,
                'code' => 'lg',
                'name' => 'Ganda',
                'endonym' => 'Luganda',
                'created_at' => null,
                'updated_at' => null,
            ],
            111 => [
                'id' => 112,
                'code' => 'li',
                'name' => 'Limburgan|Limburger|Limburgish',
                'endonym' => 'Limburgs',
                'created_at' => null,
                'updated_at' => null,
            ],
            112 => [
                'id' => 113,
                'code' => 'ln',
                'name' => 'Lingala',
                'endonym' => 'Lingála',
                'created_at' => null,
                'updated_at' => null,
            ],
            113 => [
                'id' => 114,
                'code' => 'lo',
                'name' => 'Lao',
                'endonym' => 'ພາສາລາວ',
                'created_at' => null,
                'updated_at' => null,
            ],
            114 => [
                'id' => 115,
                'code' => 'lt',
                'name' => 'Lithuanian',
                'endonym' => 'lietuvių kalba',
                'created_at' => null,
                'updated_at' => null,
            ],
            115 => [
                'id' => 116,
                'code' => 'lu',
                'name' => 'Luba-Katanga',
                'endonym' => 'Tshiluba',
                'created_at' => null,
                'updated_at' => null,
            ],
            116 => [
                'id' => 117,
                'code' => 'lv',
                'name' => 'Latvian',
                'endonym' => 'latviešu valoda',
                'created_at' => null,
                'updated_at' => null,
            ],
            117 => [
                'id' => 118,
                'code' => 'mg',
                'name' => 'Malagasy',
                'endonym' => 'Malagasy fiteny',
                'created_at' => null,
                'updated_at' => null,
            ],
            118 => [
                'id' => 119,
                'code' => 'mh',
                'name' => 'Marshallese',
                'endonym' => 'Kajin M̧ajeļ',
                'created_at' => null,
                'updated_at' => null,
            ],
            119 => [
                'id' => 120,
                'code' => 'mi',
                'name' => 'Maori',
                'endonym' => 'te reo Māori',
                'created_at' => null,
                'updated_at' => null,
            ],
            120 => [
                'id' => 121,
                'code' => 'mk',
                'name' => 'Macedonian',
                'endonym' => 'македонски јазик',
                'created_at' => null,
                'updated_at' => null,
            ],
            121 => [
                'id' => 122,
                'code' => 'ml',
                'name' => 'Malayalam',
                'endonym' => 'മലയാളം',
                'created_at' => null,
                'updated_at' => null,
            ],
            122 => [
                'id' => 123,
                'code' => 'mn',
                'name' => 'Mongolian',
                'endonym' => 'монгол',
                'created_at' => null,
                'updated_at' => null,
            ],
            123 => [
                'id' => 124,
                'code' => 'mr',
                'name' => 'Marathi',
                'endonym' => 'मराठी',
                'created_at' => null,
                'updated_at' => null,
            ],
            124 => [
                'id' => 125,
                'code' => 'ms',
                'name' => 'Malay',
                'endonym' => 'bahasa Melayu|بهاس ملايو',
                'created_at' => null,
                'updated_at' => null,
            ],
            125 => [
                'id' => 126,
                'code' => 'mt',
                'name' => 'Maltese',
                'endonym' => 'Malti',
                'created_at' => null,
                'updated_at' => null,
            ],
            126 => [
                'id' => 127,
                'code' => 'my',
                'name' => 'Burmese',
                'endonym' => 'ဗမာစာ',
                'created_at' => null,
                'updated_at' => null,
            ],
            127 => [
                'id' => 128,
                'code' => 'na',
                'name' => 'Nauru',
                'endonym' => 'Ekakairũ Naoero',
                'created_at' => null,
                'updated_at' => null,
            ],
            128 => [
                'id' => 129,
                'code' => 'nb',
                'name' => 'Bokm',
                'endonym' => 'Norsk bokmål',
                'created_at' => null,
                'updated_at' => null,
            ],
            129 => [
                'id' => 130,
                'code' => 'nd',
                'name' => 'Ndebele, North|North Ndebele',
                'endonym' => 'isiNdebele|Ndebele',
                'created_at' => null,
                'updated_at' => null,
            ],
            130 => [
                'id' => 131,
                'code' => 'ndc',
                'name' => 'Ndau',
                'endonym' => 'chiNdau|Chindau|Ndzawu|Njao|Sofala|Southeast Shona|Chidanda',
                'created_at' => null,
                'updated_at' => null,
            ],
            131 => [
                'id' => 132,
                'code' => 'ne',
                'name' => 'Nepali',
                'endonym' => 'नेपाली',
                'created_at' => null,
                'updated_at' => null,
            ],
            132 => [
                'id' => 133,
                'code' => 'ng',
                'name' => 'Ndonga',
                'endonym' => 'Owambo',
                'created_at' => null,
                'updated_at' => null,
            ],
            133 => [
                'id' => 134,
                'code' => 'niu',
                'name' => 'Niuean',
                'endonym' => 'ko e vagahau Niuē',
                'created_at' => null,
                'updated_at' => null,
            ],
            134 => [
                'id' => 135,
                'code' => 'nl',
                'name' => 'Dutch|Flemish',
                'endonym' => 'Nederlands|Vlaams',
                'created_at' => null,
                'updated_at' => null,
            ],
            135 => [
                'id' => 136,
                'code' => 'nmq',
                'name' => 'Nambya',
                'endonym' => 'Nambya',
                'created_at' => null,
                'updated_at' => null,
            ],
            136 => [
                'id' => 137,
                'code' => 'nn',
                'name' => 'Norwegian Nynorsk|Nynorsk, Norwegian',
                'endonym' => 'Norsk nynorsk',
                'created_at' => null,
                'updated_at' => null,
            ],
            137 => [
                'id' => 138,
                'code' => 'no',
                'name' => 'Norwegian',
                'endonym' => 'Norsk',
                'created_at' => null,
                'updated_at' => null,
            ],
            138 => [
                'id' => 139,
                'code' => 'nr',
                'name' => 'Ndebele, South|South Ndebele',
                'endonym' => 'isiNdebele|Nrebele',
                'created_at' => null,
                'updated_at' => null,
            ],
            139 => [
                'id' => 140,
                'code' => 'nrf',
                'name' => 'Jèrriais|Guernésiais',
                'endonym' => 'Jèrriais|Guernésiais',
                'created_at' => null,
                'updated_at' => null,
            ],
            140 => [
                'id' => 141,
                'code' => 'nso',
                'name' => 'Northern Sotho|Pedi',
                'endonym' => 'Sesotho sa Leboa|Sepedi',
                'created_at' => null,
                'updated_at' => null,
            ],
            141 => [
                'id' => 142,
                'code' => 'nv',
                'name' => 'Navajo|Navaho',
                'endonym' => 'Diné bizaad|Dinékʼehǰí',
                'created_at' => null,
                'updated_at' => null,
            ],
            142 => [
                'id' => 143,
                'code' => 'ny',
                'name' => 'Chichewa|Chewa|Nyanja',
                'endonym' => 'chiCheŵa|chinyanja',
                'created_at' => null,
                'updated_at' => null,
            ],
            143 => [
                'id' => 144,
                'code' => 'oc',
                'name' => 'Occitan (post 1500)|Proven',
                'endonym' => 'occitan|lenga d\'òc',
                'created_at' => null,
                'updated_at' => null,
            ],
            144 => [
                'id' => 145,
                'code' => 'oj',
                'name' => 'Ojibwa',
                'endonym' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
                'created_at' => null,
                'updated_at' => null,
            ],
            145 => [
                'id' => 146,
                'code' => 'om',
                'name' => 'Oromo',
                'endonym' => 'Afaan Oromoo',
                'created_at' => null,
                'updated_at' => null,
            ],
            146 => [
                'id' => 147,
                'code' => 'or',
                'name' => 'Oriya',
                'endonym' => 'ଓଡ଼ିଆ',
                'created_at' => null,
                'updated_at' => null,
            ],
            147 => [
                'id' => 148,
                'code' => 'os',
                'name' => 'Ossetian|Ossetic',
                'endonym' => 'ирон æвзаг',
                'created_at' => null,
                'updated_at' => null,
            ],
            148 => [
                'id' => 149,
                'code' => 'pa',
                'name' => 'Panjabi|Punjabi',
                'endonym' => 'ਪੰਜਾਬੀ|پنجابی',
                'created_at' => null,
                'updated_at' => null,
            ],
            149 => [
                'id' => 150,
                'code' => 'pal',
                'name' => 'Pahlavi|Middle Persian',
                'endonym' => '??????|Pārsīk|Pārsīg',
                'created_at' => null,
                'updated_at' => null,
            ],
            150 => [
                'id' => 151,
                'code' => 'pap',
                'name' => 'Papiamento',
                'endonym' => 'Papiamentu',
                'created_at' => null,
                'updated_at' => null,
            ],
            151 => [
                'id' => 152,
                'code' => 'pi',
                'name' => 'Pali',
                'endonym' => 'पाऴि',
                'created_at' => null,
                'updated_at' => null,
            ],
            152 => [
                'id' => 153,
                'code' => 'pih',
                'name' => 'Pitcairn-Norfolk|Pitkern|Pitcairnese',
                'endonym' => 'Pitkern-Norfolk|Pitkern-Norfolk',
                'created_at' => null,
                'updated_at' => null,
            ],
            153 => [
                'id' => 154,
                'code' => 'pl',
                'name' => 'Polish',
                'endonym' => 'język polski|polszczyzna',
                'created_at' => null,
                'updated_at' => null,
            ],
            154 => [
                'id' => 155,
                'code' => 'prs',
                'name' => 'Dari|Dari Persian|Afghan Persian',
                'endonym' => 'دری|Darī|فارسی دری|Fārsī-ye Darī',
                'created_at' => null,
                'updated_at' => null,
            ],
            155 => [
                'id' => 156,
                'code' => 'ps',
                'name' => 'Pushto|Pashto',
                'endonym' => 'پښتو',
                'created_at' => null,
                'updated_at' => null,
            ],
            156 => [
                'id' => 157,
                'code' => 'pt',
                'name' => 'Portuguese',
                'endonym' => 'português',
                'created_at' => null,
                'updated_at' => null,
            ],
            157 => [
                'id' => 158,
                'code' => 'qu',
                'name' => 'Quechua',
                'endonym' => 'Runa Simi|Kichwa',
                'created_at' => null,
                'updated_at' => null,
            ],
            158 => [
                'id' => 159,
                'code' => 'rm',
                'name' => 'Romansh',
                'endonym' => 'rumantsch grischun',
                'created_at' => null,
                'updated_at' => null,
            ],
            159 => [
                'id' => 160,
                'code' => 'rn',
                'name' => 'Rundi',
                'endonym' => 'Ikirundi',
                'created_at' => null,
                'updated_at' => null,
            ],
            160 => [
                'id' => 161,
                'code' => 'ro',
                'name' => 'Romanian|Moldavian|Moldovan',
                'endonym' => 'limba română|limba moldovenească',
                'created_at' => null,
                'updated_at' => null,
            ],
            161 => [
                'id' => 162,
                'code' => 'ru',
                'name' => 'Russian',
                'endonym' => 'русский язык',
                'created_at' => null,
                'updated_at' => null,
            ],
            162 => [
                'id' => 163,
                'code' => 'rw',
                'name' => 'Kinyarwanda',
                'endonym' => 'Ikinyarwanda',
                'created_at' => null,
                'updated_at' => null,
            ],
            163 => [
                'id' => 164,
                'code' => 'sa',
                'name' => 'Sanskrit',
                'endonym' => 'संस्कृतम्',
                'created_at' => null,
                'updated_at' => null,
            ],
            164 => [
                'id' => 165,
                'code' => 'sc',
                'name' => 'Sardinian',
                'endonym' => 'sardu',
                'created_at' => null,
                'updated_at' => null,
            ],
            165 => [
                'id' => 166,
                'code' => 'sd',
                'name' => 'Sindhi',
                'endonym' => 'सिन्धी|سنڌي، سندھی',
                'created_at' => null,
                'updated_at' => null,
            ],
            166 => [
                'id' => 167,
                'code' => 'se',
                'name' => 'Northern Sami',
                'endonym' => 'Davvisámegiella',
                'created_at' => null,
                'updated_at' => null,
            ],
            167 => [
                'id' => 168,
                'code' => 'sg',
                'name' => 'Sango',
                'endonym' => 'yângâ tî sängö',
                'created_at' => null,
                'updated_at' => null,
            ],
            168 => [
                'id' => 169,
                'code' => 'si',
                'name' => 'Sinhala|Sinhalese',
                'endonym' => 'සිංහල',
                'created_at' => null,
                'updated_at' => null,
            ],
            169 => [
                'id' => 170,
                'code' => 'sk',
                'name' => 'Slovak',
                'endonym' => 'slovenčina|slovenský jazyk',
                'created_at' => null,
                'updated_at' => null,
            ],
            170 => [
                'id' => 171,
                'code' => 'sl',
                'name' => 'Slovenian',
                'endonym' => 'slovenski jezik|slovenščina',
                'created_at' => null,
                'updated_at' => null,
            ],
            171 => [
                'id' => 172,
                'code' => 'sm',
                'name' => 'Samoan',
                'endonym' => 'gagana fa\'a Samoa',
                'created_at' => null,
                'updated_at' => null,
            ],
            172 => [
                'id' => 173,
                'code' => 'sn',
                'name' => 'Shona',
                'endonym' => 'chiShona',
                'created_at' => null,
                'updated_at' => null,
            ],
            173 => [
                'id' => 174,
                'code' => 'so',
                'name' => 'Somali',
                'endonym' => 'Soomaaliga|af Soomaali',
                'created_at' => null,
                'updated_at' => null,
            ],
            174 => [
                'id' => 175,
                'code' => 'sq',
                'name' => 'Albanian',
                'endonym' => 'gjuha shqipe',
                'created_at' => null,
                'updated_at' => null,
            ],
            175 => [
                'id' => 176,
                'code' => 'sr',
                'name' => 'Serbian',
                'endonym' => 'српски језик',
                'created_at' => null,
                'updated_at' => null,
            ],
            176 => [
                'id' => 177,
                'code' => 'ss',
                'name' => 'Swati',
                'endonym' => 'SiSwati',
                'created_at' => null,
                'updated_at' => null,
            ],
            177 => [
                'id' => 178,
                'code' => 'st',
                'name' => 'Sotho, Southern',
                'endonym' => 'Sesotho',
                'created_at' => null,
                'updated_at' => null,
            ],
            178 => [
                'id' => 179,
                'code' => 'su',
                'name' => 'Sundanese',
                'endonym' => 'Basa Sunda',
                'created_at' => null,
                'updated_at' => null,
            ],
            179 => [
                'id' => 180,
                'code' => 'sv',
                'name' => 'Swedish',
                'endonym' => 'svenska',
                'created_at' => null,
                'updated_at' => null,
            ],
            180 => [
                'id' => 181,
                'code' => 'sw',
                'name' => 'Swahili',
                'endonym' => 'Kiswahili',
                'created_at' => null,
                'updated_at' => null,
            ],
            181 => [
                'id' => 182,
                'code' => 'ta',
                'name' => 'Tamil',
                'endonym' => 'தமிழ்',
                'created_at' => null,
                'updated_at' => null,
            ],
            182 => [
                'id' => 183,
                'code' => 'tdt',
                'name' => 'Tetun Dili',
                'endonym' => 'Tetun Dili|Tetun Prasa',
                'created_at' => null,
                'updated_at' => null,
            ],
            183 => [
                'id' => 184,
                'code' => 'te',
                'name' => 'Telugu',
                'endonym' => 'తెలుగు',
                'created_at' => null,
                'updated_at' => null,
            ],
            184 => [
                'id' => 185,
                'code' => 'tg',
                'name' => 'Tajik',
                'endonym' => 'тоҷикӣ|toğikī|تاجیکی',
                'created_at' => null,
                'updated_at' => null,
            ],
            185 => [
                'id' => 186,
                'code' => 'th',
                'name' => 'Thai',
                'endonym' => 'ไทย',
                'created_at' => null,
                'updated_at' => null,
            ],
            186 => [
                'id' => 187,
                'code' => 'ti',
                'name' => 'Tigrinya',
                'endonym' => 'ትግርኛ',
                'created_at' => null,
                'updated_at' => null,
            ],
            187 => [
                'id' => 188,
                'code' => 'tk',
                'name' => 'Turkmen',
                'endonym' => 'Türkmen|Түркмен',
                'created_at' => null,
                'updated_at' => null,
            ],
            188 => [
                'id' => 189,
                'code' => 'tkl',
                'name' => 'Tokelauan',
                'endonym' => 'Tokelau',
                'created_at' => null,
                'updated_at' => null,
            ],
            189 => [
                'id' => 190,
                'code' => 'tl',
                'name' => 'Tagalog',
                'endonym' => 'Wikang Tagalog|ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
                'created_at' => null,
                'updated_at' => null,
            ],
            190 => [
                'id' => 191,
                'code' => 'tn',
                'name' => 'Tswana',
                'endonym' => 'Setswana',
                'created_at' => null,
                'updated_at' => null,
            ],
            191 => [
                'id' => 192,
                'code' => 'to',
                'name' => 'Tonga (Tonga Islands)',
                'endonym' => 'faka Tonga',
                'created_at' => null,
                'updated_at' => null,
            ],
            192 => [
                'id' => 193,
                'code' => 'toi',
                'name' => 'Tonga (Zambia)|Zambezi',
                'endonym' => 'Chitonga',
                'created_at' => null,
                'updated_at' => null,
            ],
            193 => [
                'id' => 194,
                'code' => 'tpi',
                'name' => 'Tok Pisin',
                'endonym' => 'Tok Pisin',
                'created_at' => null,
                'updated_at' => null,
            ],
            194 => [
                'id' => 195,
                'code' => 'tr',
                'name' => 'Turkish',
                'endonym' => 'Türkçe',
                'created_at' => null,
                'updated_at' => null,
            ],
            195 => [
                'id' => 196,
                'code' => 'ts',
                'name' => 'Tsonga',
                'endonym' => 'Xitsonga',
                'created_at' => null,
                'updated_at' => null,
            ],
            196 => [
                'id' => 197,
                'code' => 'tt',
                'name' => 'Tatar',
                'endonym' => 'татар теле|tatar tele',
                'created_at' => null,
                'updated_at' => null,
            ],
            197 => [
                'id' => 198,
                'code' => 'tvl',
                'name' => 'Tuvaluan|Tuvalu',
                'endonym' => 'Te Ggana Tuuvalu|Te Gagana Tuuvalu',
                'created_at' => null,
                'updated_at' => null,
            ],
            198 => [
                'id' => 199,
                'code' => 'tw',
                'name' => 'Twi',
                'endonym' => 'Twi',
                'created_at' => null,
                'updated_at' => null,
            ],
            199 => [
                'id' => 200,
                'code' => 'ty',
                'name' => 'Tahitian',
                'endonym' => 'Reo Tahiti',
                'created_at' => null,
                'updated_at' => null,
            ],
            200 => [
                'id' => 201,
                'code' => 'ug',
                'name' => 'Uighur|Uyghur',
                'endonym' => 'Uyƣurqə|ئۇيغۇرچە',
                'created_at' => null,
                'updated_at' => null,
            ],
            201 => [
                'id' => 202,
                'code' => 'uk',
                'name' => 'Ukrainian',
                'endonym' => 'українська мова',
                'created_at' => null,
                'updated_at' => null,
            ],
            202 => [
                'id' => 203,
                'code' => 'ur',
                'name' => 'Urdu',
                'endonym' => 'اردو',
                'created_at' => null,
                'updated_at' => null,
            ],
            203 => [
                'id' => 204,
                'code' => 'uz',
                'name' => 'Uzbek',
                'endonym' => 'O\'zbek|Ўзбек|أۇزبېك',
                'created_at' => null,
                'updated_at' => null,
            ],
            204 => [
                'id' => 205,
                'code' => 've',
                'name' => 'Venda',
                'endonym' => 'Tshivenḓa',
                'created_at' => null,
                'updated_at' => null,
            ],
            205 => [
                'id' => 206,
                'code' => 'vi',
                'name' => 'Vietnamese',
                'endonym' => 'Tiếng Việt',
                'created_at' => null,
                'updated_at' => null,
            ],
            206 => [
                'id' => 207,
                'code' => 'vo',
                'name' => 'Volap',
                'endonym' => 'Volapük',
                'created_at' => null,
                'updated_at' => null,
            ],
            207 => [
                'id' => 208,
                'code' => 'wa',
                'name' => 'Walloon',
                'endonym' => 'walon',
                'created_at' => null,
                'updated_at' => null,
            ],
            208 => [
                'id' => 209,
                'code' => 'wo',
                'name' => 'Wolof',
                'endonym' => 'Wollof',
                'created_at' => null,
                'updated_at' => null,
            ],
            209 => [
                'id' => 210,
                'code' => 'xh',
                'name' => 'Xhosa',
                'endonym' => 'isiXhosa',
                'created_at' => null,
                'updated_at' => null,
            ],
            210 => [
                'id' => 211,
                'code' => 'yi',
                'name' => 'Yiddish',
                'endonym' => 'ייִדיש',
                'created_at' => null,
                'updated_at' => null,
            ],
            211 => [
                'id' => 212,
                'code' => 'yo',
                'name' => 'Yoruba',
                'endonym' => 'Yorùbá',
                'created_at' => null,
                'updated_at' => null,
            ],
            212 => [
                'id' => 213,
                'code' => 'za',
                'name' => 'Zhuang|Chuang',
                'endonym' => 'Saɯ cueŋƅ|Saw cuengh',
                'created_at' => null,
                'updated_at' => null,
            ],
            213 => [
                'id' => 214,
                'code' => 'zdj',
                'name' => 'Comorian|Ngazidja',
                'endonym' => 'Shikomori|Shimasiwa|شِكُمُرِ',
                'created_at' => null,
                'updated_at' => null,
            ],
            214 => [
                'id' => 215,
                'code' => 'zh',
                'name' => 'Chinese',
                'endonym' => '中文 (Zhōngwén)|汉语|漢語',
                'created_at' => null,
                'updated_at' => null,
            ],
            215 => [
                'id' => 216,
                'code' => 'zu',
                'name' => 'Zulu',
                'endonym' => 'isiZulu',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);

    }
}
